# W4A16 Quantization Configuration

method: "w4a16"
bits: 4
calibration_samples: 512
output_path: "./quantized_models/w4a16"
ignore:
  - "esm.embeddings"
  - "esm.contact_head"
  - "lm_head"
  - "classifier"
